from typing import Protocol, runtime_checkable


@runtime_checkable
class OsSystemCall(Protocol):
    def shutdown(self) -> None: ...
    def restart(self) -> None: ...
    def hibernate(self) -> None: ...
    def sleep(self) -> None: ...
    def run_file_with_default_app(self, file_path: str) -> None: ...
    def run_file_with_default_as_admin(self, file_path: str) -> None: ...
    def _is_could_run_as_admin(self) -> bool: ...
    def stop_process_by_name(self, process_name: str) -> None: ...
